{{--
    Branded quotation / invoice — the Finance team's approved Coffee and FET
    designs, rebuilt as a real layout (data: App\Support\BrandedDocument).
    Measurements follow the design artwork scaled to an A4 page at 96 dpi
    (794 × 1123 px). Artwork comes from resources/document-art, generated by
    scripts/generate_document_art.py.
--}}
@php($a = $d['art'])
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @font-face { font-family: 'Open Sans'; font-weight: normal; src: url('{{ $a }}/fonts/OpenSans-Regular.ttf') format('truetype'); }
    @font-face { font-family: 'Open Sans'; font-weight: bold; src: url('{{ $a }}/fonts/OpenSans-Bold.ttf') format('truetype'); }
    @page { margin: 0 0 48px 0; }
    * { box-sizing: border-box; }
    body { margin: 0; font-family: 'Open Sans', DejaVu Sans, sans-serif; color: #1a1a1a; font-size: 12.5px; }
    .wrap { padding: 0 33px; }
    .abs { position: absolute; }

    /* Header */
    .head { position: relative; height: 339px; }
    .contact td { font-size: 12.6px; color: #1e1e1e; vertical-align: top; padding: 0; }
    .contact img { width: 22px; height: 22px; }

    /* Customer / information boxes */
    table.boxes { width: 728px; border-collapse: separate; border-spacing: 0; }
    .bar { position: relative; height: 33px; }
    .bar img { position: absolute; left: 0; top: 0; width: 358px; height: 33px; }
    .bar span { position: absolute; left: 50px; top: 9px; color: #fff; font-weight: bold; font-size: 13.5px; letter-spacing: .02em; }
    .body { background: #f2f3f5; border: 1px solid #dde0e3; border-top: 0; border-radius: 0 0 6px 6px; padding: 7px 14px 6px 18px; vertical-align: top; height: 104px; }
    .cust div { font-size: 12.8px; line-height: 17px; }
    .cust .bold { font-weight: bold; }
    table.info { width: 100%; border-collapse: collapse; }
    table.info td { font-size: 11.8px; line-height: 13.6px; padding: 0 0 0.6px; vertical-align: top; }
    table.info td.k { width: 118px; }
    table.info td.c { width: 16px; }
    .blank { display: inline-block; width: 180px; border-bottom: 1px solid #555; height: 12px; }

    /* Items */
    table.items { width: 728px; border-collapse: collapse; margin-top: 8px; }
    table.items th { background: #565a5d; color: #fff; font-size: 12px; font-weight: bold; text-transform: uppercase; padding: 6px 10px; text-align: left; border-right: 1px solid #7d8184; letter-spacing: .02em; }
    table.items th:last-child { border-right: 0; }
    table.items th.ctr, table.items td.ctr { text-align: center; }
    table.items th.num, table.items td.num { text-align: right; }
    table.items td { border-bottom: 1px solid #d9dcdf; border-right: 1px solid #d9dcdf; padding: 3px 10px 4px; vertical-align: top; font-size: 11.8px; line-height: 14px; }
    table.items td:first-child { border-left: 1px solid #d9dcdf; text-align: center; }
    table.items td:last-child { border-right: 1px solid #d9dcdf; }
    table.items tr { page-break-inside: avoid; }
    .nm { font-weight: bold; font-size: 12px; line-height: 14px; }
    .dt { font-size: 10px; line-height: 11.8px; color: #262626; }

    /* Totals */
    .totals { position: relative; height: 76px; width: 327px; margin: 5px 0 0 401px; page-break-inside: avoid; }
    .totals img { position: absolute; left: 0; top: 0; width: 327px; height: 76px; }
    .totals .l, .totals .v { position: absolute; font-weight: bold; }
    .totals .l { left: 16px; color: #fff; font-size: 12.4px; }
    .totals .v { right: 14px; text-align: right; color: #111; font-size: 12.6px; }
    .totals .g { color: #111; font-size: 14.5px; }

    /* Sections */
    .section { margin-top: 7px; page-break-inside: avoid; }
    .section.beside { margin-top: -28px; }
    .sec-title { border-collapse: collapse; }
    .sec-title td { vertical-align: middle; padding: 0; height: 25px; }
    .sec-title .t { color: #9c6416; font-weight: bold; font-size: 15px; text-transform: uppercase; letter-spacing: .01em; padding-left: 10px; }
    .rule { height: 4px; line-height: 0; font-size: 0; overflow: hidden; margin-top: 2px; }
    .rule img { width: 728px; height: 4px; }
    .panel { background: #f4f5f6; padding: 6px 22px 3px; border-radius: 0 0 4px 4px; }
    table.terms { width: 100%; border-collapse: collapse; }
    table.terms td { font-size: 10.6px; line-height: 12.8px; vertical-align: top; padding: 0 0 3px; }
    table.terms td.k { width: 160px; font-weight: bold; }
    table.terms td.c { width: 18px; }
    ol.list { margin: 0; padding-left: 18px; }
    ol.list li { font-size: 10.6px; line-height: 13.6px; }

    /* Acceptance */
    .accept p { margin: 0 0 2px; font-size: 10.8px; }
    table.sign { width: 100%; border-collapse: collapse; }
    table.sign td { font-size: 11px; padding: 2px 0 4px; vertical-align: bottom; }
    table.sign td.k { width: 58px; }
    table.sign td.k2 { width: 100px; padding-left: 40px; }
    table.sign .line { border-bottom: 1px solid #555; height: 12px; }

    /* Footer (every page) */
    .footer { position: fixed; left: 0; right: 0; bottom: -48px; height: 48px; }
    .footer .fr { position: absolute; left: 33px; top: 0; width: 728px; height: 4px; }
    .footer .ft { position: absolute; left: 33px; top: 20px; font-size: 8.4px; color: #333; }
    .footer .ft b { color: #111; }
    .footer .sep { color: #c49a46; padding: 0 5px; }
    .footer .tab { position: absolute; right: 0; top: 8px; width: 274px; height: 32px; }
    .footer .tab img { position: absolute; left: 0; top: 0; width: 274px; height: 32px; }
    .footer .tab span { position: absolute; right: 26px; top: 10px; color: #fff; font-size: 9.6px; }
</style>
</head>
<body>

<div class="footer">
    <img class="fr" src="{{ $a }}/rule-footer.png">
    <div class="ft"><b>{{ $d['company']['name'] }}</b><span class="sep">|</span>{{ implode(' ', $d['company']['address']) }}@if($d['company']['tin'])<span class="sep">|</span>TIN: {{ $d['company']['tin'] }}@endif</div>
    <div class="tab"><img src="{{ $a }}/footer-tab.png"><span>{{ $d['footer_tab'] }}</span></div>
</div>

{{-- ══ Header ══════════════════════════════════════════════════════════ --}}
<div class="head">
    <img class="abs" src="{{ $d['header'] }}" style="left:249px; top:0; width:545px; height:339px;">
    <img class="abs" src="{{ $a }}/logo.png" style="left:53px; top:11px; width:182px; height:168px;">
    <table class="contact abs" style="left:29px; top:188px; border-collapse:collapse;">
        <tr><td style="width:33px; padding-top:1px;"><img src="{{ $a }}/ic-pin.png"></td><td style="line-height:17.5px; padding-bottom:6px;">{!! implode('<br>', array_map('e', $d['company']['address'])) !!}</td></tr>
        <tr><td style="padding-top:0;"><img src="{{ $a }}/ic-phone.png"></td><td style="padding-top:3px; height:22px;">{{ $d['company']['phone'] }}</td></tr>
        <tr><td><img src="{{ $a }}/ic-mail.png"></td><td style="padding-top:3px; height:22px;">{{ $d['company']['email'] }}</td></tr>
        @if($d['company']['tin'])
        <tr><td><img src="{{ $a }}/ic-building.png"></td><td style="padding-top:3px; height:22px;">TIN: {{ $d['company']['tin'] }}</td></tr>
        @endif
    </table>
</div>

<div class="wrap">
    {{-- ══ Customer + document information ════════════════════════════ --}}
    <table class="boxes">
        <tr>
            <td style="width:358px; padding:0;"><div class="bar"><img src="{{ $a }}/bar-person.png"><span>{{ $d['customer_title'] }}</span></div></td>
            <td style="width:12px; padding:0;"></td>
            <td style="width:358px; padding:0;"><div class="bar"><img src="{{ $a }}/bar-document.png"><span>{{ $d['info_title'] }}</span></div></td>
        </tr>
        <tr>
            <td class="body cust">
                @foreach($d['customer'] as [$style, $line])
                    <div class="{{ $style }}">{{ $line }}</div>
                @endforeach
            </td>
            <td style="padding:0;"></td>
            <td class="body">
                <table class="info">
                    @foreach($d['info'] as [$k, $v])
                        <tr><td class="k">{{ $k }}</td><td class="c">:</td><td>@if(filled($v)){!! nl2br(e($v)) !!}@else<span class="blank"></span>@endif</td></tr>
                    @endforeach
                </table>
            </td>
        </tr>
    </table>

    {{-- ══ Items ════════════════════════════════════════════════════════ --}}
    <table class="items">
        <thead>
            <tr>
                @if($d['business'] === 'coffee')
                    <th class="ctr" style="width:27px;">No.</th>
                    <th>Description</th>
                    <th class="ctr" style="width:83px;">Quantity</th>
                    <th class="ctr" style="width:107px;">Unit Price ({{ $d['currency'] }})</th>
                    <th class="ctr" style="width:116px;">Total Price ({{ $d['currency'] }})</th>
                @else
                    <th class="ctr" style="width:30px;">No.</th>
                    <th>Description</th>
                    <th class="ctr" style="width:55px;">Qty</th>
                    <th class="ctr" style="width:53px;">Unit</th>
                    <th class="ctr" style="width:137px;">Unit Price ({{ $d['currency'] }})</th>
                    <th class="ctr" style="width:132px;">Total Price ({{ $d['currency'] }})</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @foreach($d['items'] as $it)
                <tr>
                    <td>{{ $it['no'] }}</td>
                    <td><div class="nm">{{ $it['name'] }}</div>@if($it['details'])<div class="dt">{!! nl2br(e($it['details'])) !!}</div>@endif</td>
                    @if($d['business'] === 'coffee')
                        <td class="ctr">{{ $it['qty_unit'] }}</td>
                        <td class="ctr">{{ $it['unit_price'] }}</td>
                        <td class="num">{{ $it['total'] }}</td>
                    @else
                        <td class="ctr" style="vertical-align:middle;">{{ $it['qty'] }}</td>
                        <td class="ctr" style="vertical-align:middle;">{{ $it['unit'] }}</td>
                        <td class="ctr" style="vertical-align:middle;">{{ $it['unit_price'] }}</td>
                        <td class="ctr" style="vertical-align:middle;">{{ $it['total'] }}</td>
                    @endif
                </tr>
            @endforeach
        </tbody>
    </table>

    {{-- ══ Totals ═══════════════════════════════════════════════════════ --}}
    <div class="totals">
        <img src="{{ $a }}/totals.png">
        <span class="l" style="top:6px;">{{ $d['totals'][0][0] }}</span><span class="v" style="top:6px;">{{ $d['totals'][0][1] }}</span>
        <span class="l" style="top:30px;">{{ $d['totals'][1][0] }}</span><span class="v" style="top:30px;">{{ $d['totals'][1][1] }}</span>
        <span class="l g" style="top:55px; font-size:13.4px;">{{ $d['totals'][2][0] }}</span><span class="v g" style="top:53.5px;">{{ $d['totals'][2][1] }}</span>
    </div>

    {{-- ══ Terms ════════════════════════════════════════════════════════ --}}
    @if(! empty($d['terms']['rows']))
        {{-- Coffee: the design sets this heading beside the foot of the totals panel. --}}
        <div class="section {{ $d['business'] === 'coffee' ? 'beside' : '' }}">
            <table class="sec-title"><tr><td><img src="{{ $a }}/ic-terms.png" style="width:30px; height:30px;"></td><td class="t">{{ $d['terms']['title'] }}</td></tr></table>
            <div class="rule"><img src="{{ $a }}/rule-gold.png"></div>
            <div class="panel">
                <table class="terms">
                    @foreach($d['terms']['rows'] as [$k, $v])
                        <tr><td class="k">{{ $k }}</td><td class="c">:</td><td>{!! nl2br(e($v)) !!}</td></tr>
                    @endforeach
                </table>
            </div>
        </div>
    @endif

    {{-- ══ Invoices: payment instructions (+ FET notes and terms) ══════════ --}}
    @if(! $d['is_quote'])
        <div class="section">
            <table class="sec-title"><tr><td><img src="{{ $a }}/ic-terms.png" style="width:30px; height:30px;"></td><td class="t">Payment Instructions</td></tr></table>
            <div class="rule"><img src="{{ $a }}/rule-gold.png"></div>
            <div class="panel">
                @if(! $d['bank'])
                    <table class="terms"><tr><td>Bank details are provided with this invoice on request. Please quote <b>{{ $d['number'] }}</b> as your payment reference.</td></tr></table>
                @elseif($d['business'] === 'coffee')
                    @php($half = (int) ceil(count($d['bank']) / 2))
                    <table style="width:100%; border-collapse:collapse;"><tr>
                        @foreach([array_slice($d['bank'], 0, $half), array_slice($d['bank'], $half)] as $col)
                            <td style="width:50%; vertical-align:top; padding:0;">
                                <table class="terms">
                                    @foreach($col as [$k, $v])
                                        <tr><td class="k" style="width:110px; font-weight:normal;">{{ $k }}</td><td class="c">:</td><td>{{ $v }}</td></tr>
                                    @endforeach
                                </table>
                            </td>
                        @endforeach
                    </tr></table>
                @else
                    <table style="width:100%; border-collapse:collapse;"><tr>
                        <td style="width:52%; vertical-align:top; padding:0;">
                            <table class="terms">
                                @foreach($d['bank'] as [$k, $v])
                                    <tr><td class="k" style="width:110px; font-weight:normal;">{{ $k }}</td><td class="c">:</td><td>{{ $v }}</td></tr>
                                @endforeach
                            </table>
                        </td>
                        <td style="vertical-align:top; padding:0 0 0 14px;">
                            <div style="font-size:11.3px; margin-bottom:3px;">Notes:</div>
                            <ol class="list">@foreach($d['notes'] as $n)<li>{{ $n }}</li>@endforeach</ol>
                        </td>
                    </tr></table>
                @endif
            </div>
        </div>
        @if($d['business'] === 'fet')
            <div class="section">
                <table class="sec-title"><tr><td><img src="{{ $a }}/ic-terms.png" style="width:30px; height:30px;"></td><td class="t">Terms &amp; Conditions</td></tr></table>
                <div class="rule"><img src="{{ $a }}/rule-gold.png"></div>
                <div class="panel"><ol class="list">@foreach($d['conditions'] as $n)<li>{{ $n }}</li>@endforeach</ol></div>
            </div>
        @endif
    @endif

    {{-- ══ Acceptance (quotations) ══════════════════════════════════════ --}}
    @if($d['acceptance'])
        <div class="section accept">
            <table class="sec-title"><tr><td><img src="{{ $a }}/ic-accept.png" style="width:43px; height:30px;"></td><td class="t">Acceptance</td></tr></table>
            <div class="rule"><img src="{{ $a }}/rule-gold.png"></div>
            <div class="panel">
                <p>To accept this quotation, please sign below or confirm acceptance in writing.</p>
                <table class="sign">
                    @foreach($d['acceptance'] as [$left, $right])
                        <tr>
                            <td class="k">{{ $left }}:</td><td><div class="line"></div></td>
                            <td class="k2">{{ $right }}:</td><td><div class="line"></div></td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    @endif
</div>
</body>
</html>
